APP_TARGET = 'GoodBitee'
PROJECT_PATH = '../node_modules/'

platform :ios, '10.0'

target APP_TARGET do
    pod 'React', :path => PROJECT_PATH + 'react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTPushNotification',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    ]
    pod 'yoga', :path => PROJECT_PATH + 'react-native/ReactCommon/yoga'
    pod 'DoubleConversion', :podspec => PROJECT_PATH + 'react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => PROJECT_PATH + 'react-native/third-party-podspecs/GLog.podspec'
    pod"" 'Folly', :podspec => PROJECT_PATH + 'react-native/third-party-podspecs/Folly.podspec'

    # React Third Party Dependancies
    pod 'RNGestureHandler', :path => PROJECT_PATH + 'react-native-gesture-handler'
    pod 'react-native-fbsdk', :path => PROJECT_PATH + 'react-native-fbsdk'
    pod 'react-native-spinkit', :path => PROJECT_PATH + 'react-native-spinkit'
    pod 'react-native-image-picker', :path => PROJECT_PATH + 'react-native-image-picker'
    #pod 'RNGoogleSignin', :path => PROJECT_PATH + 'react-native-google-signin'
    pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'
    pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
    # pod 'RNVectorIcons', :path => PROJECT_PATH + 'react-native-vector-icons'

    # native dependancies
    pod 'IQKeyboardManager'
end

