module.exports = {
	home: {
		source: require('./Home.png'),
		style: { width: 30, height: 30 }
	},
	homeSelected: {
		source: require('./home-icon.png'),
		style: { width: 30, height: 30 }
	},
	search: { source: require('./search.png'), style: { width: 30, height: 30 } },
	searchSelected: {
		source: require('./search-red.png'),
		style: { width: 30, height: 30 }
	},
	default: { source: require('./vip.jpg'), style: {} },
	login: { source: require('./loginbg.jpg'), style: {} },
	headerBg: { source: require('./headerBg.png'), style: {} },
	forwardArrow: { source: require('./forward_arrow.png'), style: {} },
	logo: { source: require('./GoodbiteLogo.png'), style: {} },

	backButton: { source: require('./back_icon.png'), style: {} },
	paymentIcon: { source: require('./back_icon.png'), style: {} },
	plusIcon: { source: require('./plus.png'), style: {} },
	downArrow: { source: require('./down_arrow.png'), style: {} },
	upArrow: { source: require('./up_arrow.png'), style: {} },
	smallImage: { source: require('./edit.png'), style: {} },
	name: { source: require('./name.png'), style: {} },
	phone: { source: require('./phone.png'), style: {} },
	password: { source: require('./password.png'), style: {} },
	email: { source: require('./email.png'), style: {} },
	help: { source: require('./help.png'), style: {} },
	promos: { source: require('./promocode.png'), style: {} },
	about: { source: require('./about.png'), style: {} },
	order: { source: require('./order.png'), style: {} },
	payment: { source: require('./payment.png'), style: {} },
	menu: { source: require('./menu.png'), style: {} },
	logout: { source: require('./logout.png'), style: {} },
	KitchenBgImg: { source: require('./KitchenBgImg.jpg'), style: {} },
	edit: { source: require('./edit_image_icon.png'), style: {} },
	menu_kitchen: { source: require('./menu_kitchen.png'), style: {} },
	account: { source: require('./account-payment.png'), style: {} },
	guide: { source: require('./guide-good-bitee.png'), style: {} },
	past_order: { source: require('./past-order.png'), style: {} },
	view_archive: { source: require('./view-archive.png'), style: {} },
	star: { source: require('./star.png'), style: {} },
	star_grey: { source: require('./star-g.png'), style: {} },
	half_star: { source: require('./half_star.png'), style: {} },
	delivery_time: { source: require('./delivery-time.png'), style: {} },
	gluten: { source: require('./gluten.png'), style: {} },
	most_popular: { source: require('./most-popular.png'), style: {} },
	rating: { source: require('./rating.png'), style: {} },
	recommended: { source: require('./recommanded.png'), style: {} },
	vegetarian: { source: require('./vergetarian.png'), style: {} },
	vegan: { source: require('./vegan.png'), style: {} },
	chiken: { source: require('./chiken.png'), style: {} },
	home_icon: { source: require('./home-icon.png'), style: {} },
	search_red: { source: require('./search-red.png'), style: {} },
	minimum_spicy: { source: require('./minimum-spicy.png'), style: {} },
	spicy: { source: require('./spicy.png'), style: {} },
	super_spicy: { source: require('./super-spicy.png'), style: {} },
	halal: { source: require('./halal.png'), style: {} },
	checkmark: { source: require('./checkmark.png'), style: {} },
	Cancel: { source: require('./Cancel.png'), style: {} },
	delete: { source: require('./delete_red.png'), style: {} }
};
